apiVersion: apps/v1
kind: Deployment
metadata:
  name: kargo-demo-web1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kargo-demo-web1
  template:
    metadata:
      labels:
        app: kargo-demo-web1
    spec:
      containers:
      - image: ghcr.io/mikakolk12/web1:sha-7ab52a4
        name: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: content
          readOnly: true
      volumes:
      - configMap:
          name: kargo-demo-web1-content
        name: content
