apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: demo-promo-process
  namespace: kargo-demo
spec:
  vars:
  - name: gitopsRepo
    value: https://github.com/MikaKolk12/kargo-demo
  - name: web1Repo
    value: ghcr.io/mikakolk12/web1
  - name: web2Repo
    value: ghcr.io/mikakolk12/web2
  steps:
  - uses: git-clone
    config:
      repoURL: ${{ vars.gitopsRepo }}
      checkout:
      - branch: main
        path: ./src
      - branch: stage/${{ ctx.stage }}
        create: true
        path: ./out

  - uses: git-clear
    config:
      path: ./out

  - uses: kustomize-set-image
    config:
      path: ./src/stages/${{ ctx.stage }}
      images:
      - image: ${{ vars.web1Repo }}
        tag: ${{ imageFrom(vars.web1Repo).Tag }}
      - image: ${{ vars.web2Repo }}
        tag: ${{ imageFrom(vars.web2Repo).Tag }}

  - uses: kustomize-build
    config:
      path: ./src/stages/${{ ctx.stage }}
      outPath: ./out

  - as: commit
    uses: git-commit
    config:
      path: ./out
      message: "Promote ${{ ctx.stage }}: ${{ imageFrom(vars.web1Repo).Tag }}"

  - uses: git-push
    config:
      path: ./out

  - uses: argocd-update
    config:
      apps:
      - name: kargo-demo-${{ ctx.stage }}
        sources:
        - repoURL: ${{ vars.gitopsRepo }}
          desiredRevision: ${{ task.outputs.commit.commit }}
