apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kargo-demo-ghcr
  namespace: kargo-demo
  labels:
    kargo.akuity.io/cred-type: image
stringData:
  repoURL: ghcr.io
  username: MikaKolk12
  password: REPLACE_WITH_GITHUB_PAT_WRITE_PACKAGES
